### ISSUE TITLE
Differences between test executions

### ISSUE THREAD

**Issue by teanocrata** [ilice/OSCapi#204]
`python manage.py test osc.tests --settings=osc.settings.dev.app_settings`

`python manage.py test --settings=osc.settings.dev.app_settings`

**Comment by jlafuentegarcia** [comment]
Parece que cuando ejecutas sin decir qué tests, da siempre este error: ElasticException: ElasticException (CLIMATE): ElasticSearch error getting climate aggrscause = TransportError(403, u'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.11.13</center>\r\n</body>\r\n</html>\r\n')

¿se te ocurre por qué? Yo voy a investigar un poco más

**Comment by teanocrata** [comment]
Pues me despista bastante lo de por separado, el elástic tiene una pequeña verificación para que solo se pueda acceder desde determinado sitios, pero no me cuadra que de una forma te deje y de otra no, miro exactamente la configuración y te digo

**Comment by teanocrata** [comment]
Pues es que no te debería dejar ejecutar ningún test contra elástic, vamos, que lo tengo configurado para que de forma directa solo se pueda acceder desde mi casa así que lo mismo la he liado con alguna configuración, cómo estás ejecutando?

**Comment by jlafuentegarcia** [comment]
Pues como dices en la incidencia, en realidad. Desde el pycharm, pero
mismos parámetros

**Comment by teanocrata** [comment]
¿Y los demás test si que te dan lo mismo? Lo digo porque a mi me dan distintos test que en los que quizá sea más sencillo entender qué pasa (por no meter la configuración de elastic de por medio). 

(En ambos casos el error del catastro es correcto, parece que ahora mismo no nos responde, el interesante es el del `test_call_update_parcel_by_catastral_code` que da la sensación de que no usa bien el mock)

Pongo los resultados de ambos:

## Pasando el módulo
`$ python manage.py test osc.tests --settings=osc.settings.dev.app_settings`

```
test_call_inspire_when_get_inspire_data (osc.tests.importer.cadastre_test.InspireImporterTest) ... ok
test_update_cadastral_information (osc.tests.importer.cadastre_test.InspireImporterTest) ... SKIP: Very very long test
test_call_update_parcel_by_catastral_code (osc.tests.management.update_parcels_test.UpdateParcelsTest) ... ok
test_fails_when_there_is_no_parcel_args (osc.tests.management.update_parcels_test.UpdateParcelsTest) ... ok
test_call_cadastre_when_public_cadastre_info (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_call_get_public_cadastre_info_when_add_public_cadastral_info (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_create_mapping (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_dont_raise_exception_even_when_cadastre_returns_404 (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_get_cadastre_data_from_cadastre_source (osc.tests.services.cadastre_test.CadastreServiceTest) ... ERROR
test_parse_public_cadastre_response_when_cadastre_returns_error (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_call_inspire_when_get_inspire_data (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_get_inspire_data_from_inspire_source (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_parse_inspire_response_when_inspire_returns_error (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_raise_exception_when_inspire_data_return_404 (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_call_elastic_when_get_aggregated_measures (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_call_elastic_when_get_closest_station (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_aggregated_measures (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_aggregated_measures_from_elastic (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_closest_station (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_closest_station_from_elastic (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_update_parcel_by_catastral_code (osc.tests.services.parcels_test.UpdateParcelTest) ... ok
test_can_login_into_admin_pages_and_logout_later (osc.tests.functional_test.NewVisitorTest) ... nosetests osc.tests --with-coverage --with-doctest --verbosity=2 --with-html --html-file=./tmp/test/nosetest.html --cover-html --cover-html-dir=./tmp/test/cover --cover-package=osc.services --cover-package=osc.importer --cover-package=osc.management --ignore-files=.*_settings.py
Creating test database for alias 'default'...
Destroying test database for alias 'default'...
ok

======================================================================
ERROR: test_get_cadastre_data_from_cadastre_source (osc.tests.services.cadastre_test.CadastreServiceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\teanocrata\Development\OSCapi\osc\tests\services\cadastre_test.py", line 133, in test_get_cadastre_data_from_cadastre_source
    self.assertTrue(parcels['control']['cudnp'] == 1, "should obtain one "
KeyError: 'control'
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): ovc.catastro.meh.es
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
HTML: ./tmp/test/nosetest.html
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
osc\importer\__init__.py                        1      0   100%
osc\importer\cadastre.py                       90      9    90%
osc\importer\inforiego.py                     123     94    24%
osc\management\__init__.py                      0      0   100%
osc\management\commands\__init__.py             0      0   100%
osc\management\commands\update_parcels.py      13      0   100%
osc\services\__init__.py                        5      0   100%
osc\services\auth.py                           65     56    14%
osc\services\cadastre.py                      261     53    80%
osc\services\climate.py                        80      0   100%
osc\services\crop.py                           23     14    39%
osc\services\feed.py                           19      7    63%
osc\services\google.py                         36      9    75%
osc\services\parcels.py                        34     13    62%
osc\services\soil.py                           19      2    89%
osc\services\users.py                          58     49    16%
---------------------------------------------------------------
TOTAL                                         827    306    63%
----------------------------------------------------------------------
Ran 22 tests in 7.490s

FAILED (SKIP=1, errors=1)
```

## Sin pasarle el módulo

`$ python manage.py test --settings=osc.settings.dev.app_settings`

```
test_call_inspire_when_get_inspire_data (osc.tests.importer.cadastre_test.InspireImporterTest) ... ok
test_update_cadastral_information (osc.tests.importer.cadastre_test.InspireImporterTest) ... SKIP: Very very long test
test_call_update_parcel_by_catastral_code (osc.tests.management.update_parcels_test.UpdateParcelsTest) ... FAIL
test_fails_when_there_is_no_parcel_args (osc.tests.management.update_parcels_test.UpdateParcelsTest) ... ok
test_call_cadastre_when_public_cadastre_info (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_call_get_public_cadastre_info_when_add_public_cadastral_info (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_create_mapping (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_dont_raise_exception_even_when_cadastre_returns_404 (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_get_cadastre_data_from_cadastre_source (osc.tests.services.cadastre_test.CadastreServiceTest) ... ERROR
test_parse_public_cadastre_response_when_cadastre_returns_error (osc.tests.services.cadastre_test.CadastreServiceTest) ... ok
test_call_inspire_when_get_inspire_data (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_get_inspire_data_from_inspire_source (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_parse_inspire_response_when_inspire_returns_error (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_raise_exception_when_inspire_data_return_404 (osc.tests.services.cadastre_test.InspireServiceTest) ... ok
test_call_elastic_when_get_aggregated_measures (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_call_elastic_when_get_closest_station (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_aggregated_measures (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_aggregated_measures_from_elastic (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_closest_station (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_get_closest_station_from_elastic (osc.tests.services.climate_test.ClimateServiceTest) ... ok
test_update_parcel_by_catastral_code (osc.tests.services.parcels_test.UpdateParcelTest) ... ok
test_can_login_into_admin_pages_and_logout_later (osc.tests.functional_test.NewVisitorTest) ... nosetests --with-coverage --with-doctest --verbosity=2 --with-html --html-file=./tmp/test/nosetest.html --cover-html --cover-html-dir=./tmp/test/cover --cover-package=osc.services --cover-package=osc.importer --cover-package=osc.management --ignore-files=.*_settings.py
Creating test database for alias 'default'...
Destroying test database for alias 'default'...
ok

======================================================================
ERROR: test_get_cadastre_data_from_cadastre_source (osc.tests.services.cadastre_test.CadastreServiceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\teanocrata\Development\OSCapi\osc\tests\services\cadastre_test.py", line 133, in test_get_cadastre_data_from_cadastre_source
    self.assertTrue(parcels['control']['cudnp'] == 1, "should obtain one "
KeyError: 'control'

======================================================================
FAIL: test_call_update_parcel_by_catastral_code (osc.tests.management.update_parcels_test.UpdateParcelsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\teanocrata\Development\OSCapi\oscenv\lib\site-packages\mock\mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "D:\teanocrata\Development\OSCapi\osc\tests\management\update_parcels_test.py", line 21, in test_call_update_parcel_by_catastral_code
    mock_update_parcel_by_cadastral_code.assert_called_with(cadastral_code)
  File "D:\teanocrata\Development\OSCapi\oscenv\lib\site-packages\mock\mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: update_parcel_by_cadastral_code('40167A00805001')
Not called
-------------------- >> begin captured stdout << ---------------------
Successfully updated parcel

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
HTML: ./tmp/test/nosetest.html
Name                                                 Stmts   Miss  Cover
------------------------------------------------------------------------
osc\importer\__init__.py                                 1      0   100%
osc\importer\cadastre.py                                90      9    90%
osc\importer\inforiego.py                              123     94    24%
osc\importer\stations.py                                40     27    33%
osc\management\__init__.py                               0      0   100%
osc\management\commands\__init__.py                      0      0   100%
osc\management\commands\create_parcels_mapping.py       11      3    73%
osc\management\commands\delete_tables.py                27     17    37%
osc\management\commands\import_inforiego_daily.py       15      7    53%
osc\management\commands\import_inforiego_hourly.py      15      7    53%
osc\management\commands\import_parcels.py               17      9    47%
osc\management\commands\import_stations.py              13      5    62%
osc\management\commands\import_weather.py               13      5    62%
osc\management\commands\update_parcels.py               13      0   100%
osc\services\__init__.py                                 5      0   100%
osc\services\auth.py                                    65     56    14%
osc\services\cadastre.py                               261     53    80%
osc\services\climate.py                                 80      0   100%
osc\services\crop.py                                    23     14    39%
osc\services\feed.py                                    19      7    63%
osc\services\google.py                                  36      9    75%
osc\services\parcels.py                                 34     13    62%
osc\services\soil.py                                    19      2    89%
osc\services\users.py                                   58     49    16%
osc\services\weather.py                                 79     57    28%
------------------------------------------------------------------------
TOTAL                                                 1057    443    58%
----------------------------------------------------------------------
Ran 22 tests in 9.430s

FAILED (SKIP=1, errors=1, failures=1)
```

**Comment by teanocrata** [comment]
Tengo que revisar si estoy haciendo bien algunos mocks en cuanto a  "the semantics of the from ... import ... statement, which imports classes and functions into the current namespace"

**Comment by jlafuentegarcia** [comment]
¿quesloquepasaba?

**Comment by teanocrata** [comment]
Estaba mockeando mal cuando hacía un from ... import, lo que no tengo claro del todo es por qué en algún caso funcionaba, creo que es porque hacía un import en otro sitio y ya lo tenía, en todo caso seguro que lo estaba haciendo mal y haciéndolo bien ya no tengo ejecuciones distintas:

para_probar.py
`from un_modulo import lo_que_sea

def cosa_a_probar():
  lo_que_sea()
`

test.py (Mal)
`
...
@mock.patch(un_modulo.lo_que_sea)
def test_cosa_a_probar_llama_a_lo_que_sea(self, mock_lo_que_sea):
  cosa_a_probar()
  mock_lo_que_sea.assert_called()
`

test.py (Bien o eso creo)
`
...
@mock.patch(para_probar.lo_que_sea)
def test_cosa_a_probar_llama_a_lo_que_sea(self, mock_lo_que_sea):
  cosa_a_probar()
  mock_lo_que_sea.assert_called()
`

**Comment by jlafuentegarcia** [comment]
Tiene medio sentido entonces.

Lo que haces con 

```
from un_modulo import lo_que_sea

def cosa_a_probar():
  lo_que_sea()
```

En realidad es dos cosas:
1. cargar el módulo un_modulo
2. asociad lo_que_sea con un_modulo.lo_que_sea en el contexto del módulo para_probar

En realidad un_modulo.lo_que_sea y para_probar.lo_que_sea son lo mismo, pero llamando al segundo aseguras que también está cargado el módulo para_probar mientras que llamando al primero no.

Lo de que funcione distinto igual ya es tema de django. Igual al poner osc.tests mira todos esos tests y los carga antes, y de la otra manera lo hace más 'lazy', según se los va encontrando.

Pero que sepas que me alegro de que lo hayas arreglado, porque me veía el fin de semana dándole vueltas al tema y no me apetecía nada de nada :-P
